(() => {
const data=window.MUYE_DATA;
const home=document.getElementById('homeView'), list=document.getElementById('listView'), search=document.getElementById('searchView');
const categoryGrid=document.getElementById('categoryGrid'), cardGrid=document.getElementById('cardGrid'), searchGrid=document.getElementById('searchGrid');
const title=document.getElementById('sectionTitle'), desc=document.getElementById('sectionDesc'), count=document.getElementById('itemCount');
const input=document.getElementById('searchInput'), clear=document.getElementById('clearSearch');
const viewer=document.getElementById('viewer'), viewerTitle=document.getElementById('viewerTitle'), viewerEnglish=document.getElementById('viewerEnglish'), viewerCategory=document.getElementById('viewerCategory'), viewerImage=document.getElementById('viewerImage'), loading=document.getElementById('imageLoading');
let current=null;
function showOnly(el){[home,list,search].forEach(x=>x.hidden=x!==el);window.scrollTo({top:0,behavior:'smooth'})}
function renderHome(){categoryGrid.innerHTML=data.categories.map(c=>`<article class="category-card" data-id="${c.id}"><div class="emoji">${c.emoji}</div><h3>${c.title}</h3><p>${c.subtitle}</p><span class="meta">${c.items.length} 项内容</span><span class="arrow">›</span></article>`).join('');categoryGrid.querySelectorAll('.category-card').forEach(el=>el.onclick=()=>openCategory(el.dataset.id))}
function cardHtml(item,cat){return `<article class="price-card"><div class="card-thumb"><img src="${item.thumb}" alt="${item.title}" loading="lazy" decoding="async"><span class="card-tag">${cat.emoji} ${cat.title}</span></div><div class="card-body"><h3>${item.title}</h3>${item.english?`<div class="en">${item.english}</div>`:''}<p>${item.description||''}</p><span class="view-link">查看高清价目表 ↗</span></div></article>`}
function bindCards(container,arr){container.querySelectorAll('.price-card').forEach((el,i)=>el.onclick=()=>openViewer(arr[i].item,arr[i].cat))}
function openCategory(id){const cat=data.categories.find(c=>c.id===id);if(!cat)return;current=cat;title.textContent=cat.title;desc.textContent=cat.subtitle;count.textContent=`${cat.items.length} 项`;const arr=cat.items.map(item=>({item,cat}));cardGrid.innerHTML=arr.map(x=>cardHtml(x.item,x.cat)).join('');bindCards(cardGrid,arr);showOnly(list)}
function doSearch(){const q=input.value.trim().toLowerCase();if(!q){showOnly(current?list:home);return}const arr=[];data.categories.forEach(cat=>cat.items.forEach(item=>{const h=`${item.title} ${item.english||''} ${item.description||''} ${cat.title}`.toLowerCase();if(h.includes(q))arr.push({item,cat})}));document.getElementById('searchTitle').textContent=`“${input.value.trim()}” 的搜索结果`;document.getElementById('searchCount').textContent=`${arr.length} 项`;document.getElementById('emptyState').hidden=arr.length>0;searchGrid.innerHTML=arr.map(x=>cardHtml(x.item,x.cat)).join('');bindCards(searchGrid,arr);showOnly(search)}
function openViewer(item,cat){viewerTitle.textContent=item.title;viewerEnglish.textContent=item.english||'';viewerCategory.textContent=`${cat.emoji} ${cat.title}`;viewer.classList.add('open');document.body.style.overflow='hidden';loading.hidden=false;loading.textContent='高清图加载中…';viewerImage.hidden=true;viewerImage.removeAttribute('src');const im=new Image();im.onload=()=>{viewerImage.src=item.full;viewerImage.hidden=false;loading.hidden=true};im.onerror=()=>loading.textContent='图片加载失败，请稍后重试。';im.src=item.full}
function closeViewer(){viewer.classList.remove('open');document.body.style.overflow='';viewerImage.removeAttribute('src')}
document.getElementById('backBtn').onclick=()=>{current=null;showOnly(home)};document.getElementById('searchBackBtn').onclick=()=>{input.value='';showOnly(current?list:home)};input.addEventListener('input',doSearch);clear.onclick=()=>{input.value='';showOnly(current?list:home)};document.querySelectorAll('[data-close-viewer]').forEach(x=>x.onclick=closeViewer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeViewer()});renderHome();showOnly(home);
})();